/*
 * The savefile helper, as bytes: what qwark writes into each game so that the
 * game can put its save data somewhere qwark can read it.
 *
 * GENERATED by src/games/sfhelper/build.sh out of the sources beside it. Do not
 * edit it by hand; edit the helper and run
 *
 *     sh src/games/sfhelper/build.sh
 *
 * from the SDK's Cygwin shell. It is committed because the helper is PowerPC
 * code the Sony cross compiler produces, and the host builds and the unit tests
 * are clang on a PC with no SDK anywhere near them: they still have to compile
 * the table, install it into the fake console and check the bytes that land.
 */
#ifndef QWARK_SFHELPER_BINS_H
#define QWARK_SFHELPER_BINS_H

#include "../core/mem.h"
#include "../core/proto.h"

/* One run of bytes at one address. A game has one, or two when it needs a stub. */
struct sf_cave {
	u32 addr;
	const u8 *bytes;
	u32 len;
};

/*
 * Everything qwark needs to install one game's helper and talk to it. The
 * addresses are the helper's own, out of src/games/sfhelper/sf_<game>.h, so this
 * file is the one place in qwark that knows them.
 */
struct sf_desc {
	u8 game_id;

	const struct sf_cave *caves;
	u8 ncaves;

	/* The words that branch the game into the caves. */
	const struct patch_word *hooks;
	u8 nhooks;

	/* The helper writes 1 here every call, so 1 means it is running. */
	u32 api_mod;
	/* The client writes 1 to either; the helper clears it when it is done. */
	u32 api_load;
	u32 api_setaside;

	/* Where the save is parked, and how much of it there is. */
	u32 aside_addr;
	u32 aside_size;
};

/* NULL for a game with no helper, and for GAME_NONE. */
const struct sf_desc *sf_desc_for_game(u8 game_id);

#endif /* QWARK_SFHELPER_BINS_H */
