/*
 * The savefile helper's shared declarations, and the switch that picks one game's
 * address table.
 *
 * This header is compiled only by the PS3 cross compiler, into code that runs
 * inside the game's own process. Nothing in qwark itself includes it: what qwark
 * carries is the generated byte arrays in src/games/sfhelper_bins.c.
 *
 * Every game function the helper calls is declared here and left undefined. The
 * link resolves each one to a hard address with --defsym, from the SF_FN_* lines
 * in the game's header, so a call compiles to a plain relative branch and the
 * game's TOC register is never touched.
 */
#ifndef QWARK_SFHELPER_H
#define QWARK_SFHELPER_H

#define SF_RAC1 1
#define SF_RAC2 2
#define SF_RAC3 3
#define SF_RAC4 4

#ifndef SF_GAME
#error "SF_GAME must be 1, 2, 3 or 4; build.sh passes it"
#endif

#if SF_GAME == SF_RAC1
#include "sf_rac1.h"
#elif SF_GAME == SF_RAC2
#include "sf_rac2.h"
#elif SF_GAME == SF_RAC3
#include "sf_rac3.h"
#elif SF_GAME == SF_RAC4
#include "sf_rac4.h"
#else
#error "SF_GAME is not a game this helper knows"
#endif

typedef unsigned char      sf_u8;
typedef unsigned short     sf_u16;
typedef unsigned int       sf_u32;

/*
 * The three address widths the helper ever reads or writes. Everything the game
 * owns is 32 bits wide, pointers included, so nothing here is ever a C pointer
 * that the 64-bit compiler would size at eight bytes.
 */
#define SF_BYTE(addr) (*(volatile sf_u8 *)(sf_u32)(addr))
#define SF_WORD(addr) (*(volatile sf_u32 *)(sf_u32)(addr))

/* How much of the save buffer one memcpy call moves. The mods all used 32 KB. */
#define SF_CHUNK 0x8000u

/* The game's own memcpy, in every game. */
void sf_memcpy(void *dst, const void *src, int len);

#if SF_GAME == SF_RAC4
/* Deadlocked calls its loader in two steps; see sfhelper.c. */
void sf_restore_saved_game(int unk, void *buf);
void sf_magic_load(void);
#else
void sf_perform_load(int unk, void *buf);
#endif

#if SF_GAME == SF_RAC1
/* RaC1's save, load and autosave menus, which the Force autosave action drives. */
void sf_save_handler(int mode);
#endif

#endif /* QWARK_SFHELPER_H */
